[package]
name = "linux-loader"
version = "0.1.0"
authors = ["Cathy Zhang <cathy.zhang@intel.com>"]
edition = "2018"
license = "Apache-2.0 AND BSD-3-Clause"

[features]
default = ["elf", "aarch64_pe"]
elf = []
bzimage = []
aarch64_pe = []

[dependencies]
vm-memory = {version = "0.1.0", features = ["backend-mmap"]}
